name: Continuos Integration
on:
  push:
  pull_request:
env:
  CARGO_TERM_COLOR: always
jobs:
  # build the crate on Linux, Windows and MacOS (can only be tested on Linux)
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust: [stable, nightly]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup update --no-self-update ${{ matrix.rust }} && rustup default ${{ matrix.rust }}
      - name: Build
        run: cargo build

  # execute all tests (requires an installed valgrind)
  test:
    runs-on: ubuntu-latest
    needs: build
    strategy:
      matrix:
        rust: [1.82, 1.83, 1.84, 1.85, 1.86, 1.87, 1.88, 1.89, 1.90, 1.91, 1.92]
    steps:
      - uses: actions/checkout@v4
      - name: Install valgrind
        run: sudo apt-get update && sudo apt-get install valgrind
      - run: rustup update --no-self-update ${{ matrix.version }} && rustup default ${{ matrix.version }}
      - name: Run tests
        run: cargo test
      - name: Run tests in release mode
        run: cargo test --release
